version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: solara
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nestjs-service:
    build: ./nestjs-service
    command: npm run start:dev
    volumes:
      - ./nestjs-service:/app
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=postgres
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - postgres
      - python-generator

  python-generator:
    build: ./python-generator
    command: python app.py
    volumes:
      - ./python-generator:/app
      - ./output:/app/output
    environment:
      - POSTGRES_HOST=postgres
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - postgres

volumes:
  postgres-data:
